### ISSUE TITLE
error:25066067:DSO support routines:dlfcn_load:could not load the shared library

### ISSUE THREAD

**Issue by idontwannachooseanotherusername** [idontwannachooseanotherusername/KrassesWebprojekt#50]
## Short description
After starting or restarting the backend, the first login or token validation fails with `error:25066067:DSO support routines:dlfcn_load:could not load the shared library`.

## Expected Behavior
Login and token validation works immediately after starting the backend.

## Current Behavior
The first login or token validation fails and returns `error:25066067:DSO support routines:dlfcn_load:could not load the shared library`. If tried again everything works as expected.

## Steps to Reproduce
1. Start or restart the backend with `npm start` or `node backend.js`
2. Go to the login page and try to login / create a new user
3. Error occurs

## Context (Environment)
OS: Ubuntu 22.04

## Possible Implementation

**Comment by idontwannachooseanotherusername** [comment]
Has to do with openssl but I'm not sure if we can fix it since it does seem to be an issue in their code because it does not occur on Windows and somehow it works if you try again.

**Comment by SerendipiTea** [comment]
prolly an external problem in the dependencies
